# Generated by Django 3.2.16 on 2022-12-20 13:05
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    Account = get_user_model()
    DJ_SU_USERNAME = os.environ.get('DJ_SU_USERNAME')
    DJ_SU_PASSWORD = os.environ.get('DJ_SU_PASSWORD')

    Account.objects.create_superuser(
        username=DJ_SU_USERNAME,
        password=DJ_SU_PASSWORD,
    )


def delete_superuser(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser)
    ]
