# Generated by Django 3.2.16 on 2022-12-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_shoppinglist_created_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together=set(),
        ),
    ]
