# Generated by Django 3.2.16 on 2022-12-07 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_favourite', models.BooleanField(default=False)),
                ('default_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_uom', models.CharField(choices=[('PCS', 'szt.'), ('PCK', 'opak.'), ('BTL', 'butelki'), ('KG', 'kg'), ('DG', 'dag'), ('G', 'g')], max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
    ]
