# Generated by Django 3.2.16 on 2022-12-14 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_uom',
            field=models.CharField(blank=True, choices=[('PCS', 'szt.'), ('PCK', 'opak.'), ('BTL', 'butelki'), ('KG', 'kg'), ('DG', 'dag'), ('G', 'g')], max_length=20, null=True),
        ),
    ]
